name: CI/CD Pipeline - Order Service

on:
  push:
    branches:
      - main
      - "feature/**"
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  quality-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Instalar Poetry
        run: pipx install poetry

      - name: Instalar dependencias
        working-directory: ./advanced_level
        run: poetry install --no-root

      - name: Ejecutar Ruff Linter
        working-directory: ./advanced_level
        run: poetry run ruff check .

      - name: Ejecutar Ruff Formatter
        working-directory: ./advanced_level
        run: poetry run ruff format --check .

      - name: Ejecutar Mypy (Type Checking)
        working-directory: ./advanced_level
        run: poetry run mypy src/

      - name: Ejecutar Pruebas (Pytest)
        working-directory: ./advanced_level
        run: poetry run pytest tests/ --cov=src/modulo01

      - name: Generar paquete distribuble (Wheel)
        working-directory: ./advanced_level
        run: poetry build

      - name: Subir artefacto Wheel
        uses: actions/upload-artifact@v4
        with:
          name: python-wheel-package
          path: ./advanced_level/dist/*.whl

  build-and-push-docker:
    needs: quality-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extraer metadatos para Docker (tags y labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long
            type=ref,event=branch
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Construir y publicar imagen de Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./advanced_level/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}